services:
  spring-boot:
    image: public.ecr.aws/v0z4u2z1/accounting-book:1.0
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - spring.datasource.username=admin
      - spring.datasource.password=123456
      - spring.datasource.url=jdbc:postgresql://postgres:5432/accountingbook?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    networks:
      - accounting-book-service-network

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=accountingbook
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - accounting-book-service-network

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    networks:
      - accounting-book-service-network

volumes:
  db-data:
    driver: local

networks:
  accounting-book-service-network:
    driver: bridge